
# using --dry-run | kubectl apply here to prevent fail if secrets already exist
- name: Create namespaces
  shell: '{{ orchestrator_tool }}
    create ns {{ item }} --dry-run=client  -o yaml | \
    {{ orchestrator_tool }} \
    apply -f -'
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  loop:
  - backend
  - frontend
  - medical
  - operations
  - payments

- name: Create image pull secret
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'templates/pull_secret/pullsecret.yml.j2') | from_yaml_all }}"
    kubeconfig: "{{ kubeconfig }}"
  loop:
  - backend
  - frontend
  - medical
  - operations
  - payments
