---
- include_tasks: image_pull_secret.yml
- include_tasks: violation_policies.yml
# - include_tasks: slack.yml
- include_tasks: deploy_demos.yml
- name: Network anomalies
  include_tasks: network_anomalies.yml
- name: Baseline processes
  include_tasks: baseline_processes.yml
- name: Add OpenShift policy exceptions
  include_tasks: openshift_policy_fix.yml
  when: 
    orchestrator == "openshift"
- include_tasks: setup_auth0.yml
  when: auth_client_id != ""
    
